FROM neo4j:latest


#
#--name testneo4j
#    -p 7474:7474
#    -p 7687:7687
#-d
#-v $HOME/neo4j/data:/data
#-v $HOME/neo4j/logs:/logs
#-v $HOME/neo4j/import:/var/lib/neo4j/import
#-v $HOME/neo4j/plugins:/plugins
#--env NEO4J_AUTH=neo4j/test1234567890




