version: "3"

services:
  db_neo4j:
    build: /neo4j/
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234567890
    volumes:
      - $HOME/neo4j/data:/data
      - ./export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins


    #    Проброс портов осуществлять в docker-compose
    #
    #    --name testneo4j
    #    -p 7474:7474
    #    -p 7687:7687
    #    -d
    #    -v $HOME/neo4j/data:/data
    #    -v $HOME/neo4j/logs:/logs
    #    -v $HOME/neo4j/import:/var/lib/neo4j/import
    #    -v $HOME/neo4j/plugins:/plugins
    #    --env NEO4J_AUTH=neo4j/test1234567890

#  db_postgre:
#  db_s4:
#  app_backend: