version: "3"

services:
  db_neo4j:
    container_name: neo4jForCourseWork
    image: neo4j
    ports:
      - "7474:7474"
      - "8687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234567890
    volumes:
      - $HOME/neo4j/data:/data
      - ./export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    #    networks:
    #      db_net:
    restart: 'no'
    #always на проде # no на dev

  db_postgre:
    container_name: postgresForCourseWork
    image: postgres
    volumes:
      - $HOME/postgresql:/var/lib/postgresql
    #        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=cw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234567890
    ports:
      - "5434:5432"

    restart: 'no'


